### ISSUE TITLE
Sort the result

### ISSUE THREAD

**Issue by fefaul** [Atreidae/Find-CsExternalFederatedContacts#1]
It would be nice, if the result is sorted. I've modified the code to sort it descending, to get a better view on the top used domains.

If you change
`$Script:FederatedDomains | ConvertTo-Html`
to

`$Script:FederatedDomains | Sort-Object -Property count -Descending | ConvertTo-Html`

Results are sorted from biggest to smallest.

**Comment by Atreidae** [comment]
Thanks for the feedback. I'll throw it in with the next version

**Comment by Atreidae** [comment]
Resolved in 1.1
