### ISSUE TITLE
Remove local domain with get-csdomain

### ISSUE THREAD

**Issue by Atreidae** [Atreidae/Find-CsExternalFederatedContacts#3]
By default the script should try to run get-csdomain and remove the local domain.

Need to add a switch to disable the behaviour

We should also just throw a warning if we aren't running with the skype4b management tools for backwards compatibility 

Thanks to @greiginsydney for the reminder!

**Comment by greiginsydney** [comment]
Get-CsSipDomain perhaps? ;-)

**Comment by Atreidae** [comment]
Resolved in 1.1
